version: '3.8'

services:
  app:
    container_name: spring-app
    image: rifkikesepara/devops4hw:latest
    ports:
      - "8081:8080"
    restart: always
    volumes:
      - app-data:/path/to/app-data

  
volumes:
  app-data: