apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: rifkikesepara/ozmenapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              value: "ozmen"
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db:5432/devops"
            - name: SPRING_DATASOURCE_USERNAME
              value: "ozmen"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
          volumeMounts:
            - name: app-data
              mountPath: /path/to/app-data
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data-pvc