name: Docker Image CI

on:
   workflow_run:
      workflows: ["Java CI with Gradle"]
      types:
        - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t ozmenapp .
    - name: Push to Dockerhub
      run: docker push rifkikesepara/ozmenapp:latest
